### ISSUE TITLE
1366 x 768 Resolution - Icons in the wrong place

### ISSUE THREAD

**Issue by SnailVendor** [nomis51/Menagerie#13]
My native resolution on my laptop is 1366 x 768 and the icons end up being in the wrong place. There doesn't seem to be an option to move the icons around either, unless I'm missing something.

![Menagerie bug](https://user-images.githubusercontent.com/79535142/108887504-a383b380-760a-11eb-8f65-a3378fb04e3d.png)

**Comment by nomis51** [comment]
Indeed, there are no option to move things around currently. This might be the way I'm gonna make the overlay more responsive for resolutions that aren't 1920x1080 and mostly for those that are lower then that.

For now, version 1.2.15-BETA, is going to hotfix that for you, by adding a small support for 1366x768 resolution.

![image](https://user-images.githubusercontent.com/25111613/108913127-8f828680-75f7-11eb-8bcc-6c57d70697e3.png)

**Comment by nomis51** [comment]
Hotfix in 1.2.15-BETA. 

Future updates will make the overlay more responsive.

**Comment by nomis51** [comment]
In the next release I'll come up with movable parts on the overlay. Good idea @SnailVendor !

Here's what it looks like and how it will works : 

By clicking the little "cog" icon at the bottom right of the screen, the movable part of the overlay will be highlighted and movable.

![image](https://user-images.githubusercontent.com/25111613/108927006-7b498400-760d-11eb-80ca-8702a78e42b6.png)

Then you grab the newly highlighted parts and drag them around. When you're done, just click again on the "cog" button.

![image](https://user-images.githubusercontent.com/25111613/108926945-640a9680-760d-11eb-9076-32974161ea37.png)


![image](https://user-images.githubusercontent.com/25111613/108927095-a3d17e00-760d-11eb-9bcb-901cd30abf88.png)


This will most likely featured  in 1.2.16-BETA update.

**Comment by nomis51** [comment]
Fixed in 1.2.16.

Overlay parts are now movable.

**Comment by SnailVendor** [comment]
Wow nice! Thanks for the really quick fix, keep up the good work.
