### ISSUE TITLE
Menagerie.exe is killed when notepad is open

### ISSUE THREAD

**Issue by shosho-san** [nomis51/Menagerie#2]
because it's a beta :)
![notepad_menagerie](https://user-images.githubusercontent.com/17947358/105068442-3c119b80-5a81-11eb-81d8-b48a12dae18b.png)

**Comment by shosho-san** [comment]
steps to reproduce:
1: open notepad.exe
2: open menagerie.exe

result: menagerie.exe is closed after few seconds

**Comment by nomis51** [comment]
Unexpected debugging code left in the code base, causing the problem.

Will be fixed in 1.2.10.

**Comment by nomis51** [comment]
fixed in 1.2.10
