### ISSUE TITLE
Fast buying with Ctrl click on whisper button on website

### ISSUE THREAD

**Issue by mafima** [nomis51/Menagerie#20]
In [Poe Trades compation](https://github.com/lemasato/POE-Trades-Companion) you can Ctrl click on a whisper to automaticly paste it into poe chat. this feature would really improve the usability if you are buying. Thanks

![image](https://user-images.githubusercontent.com/3407209/110774938-a4e5ea80-825e-11eb-9ebd-04308bf61329.png)

**Comment by nomis51** [comment]
It is currently a feature available in the app, but it's disabled by default. You can go to the Settings > Whispers, then enable "Auto whisper".

Then, you can simply click the "Whisper" button on the tradeing website, and the app will detect that's it's a whisper to buy something and it's going to send it in-game.
