### ISSUE TITLE
Chaos recipe block the first column in stash tab

### ISSUE THREAD

**Issue by shosho-san** [nomis51/Menagerie#3]
Hello again,

I cannot access to the 1st collumn, and i can't move the overlay
![chaos_recipe_quad_tab](https://user-images.githubusercontent.com/17947358/105081294-48522480-5a92-11eb-83a2-e53ded19b213.png)

my resolution: 1920*1080.
Good luck :)

**Comment by nomis51** [comment]
I had surprisingly a couples issues fixing this one 😂 seems like the framework I'm using have many solutions for this problems, but none seems to work as expected so far. 

So I'll be pushing a temporary fix while I figure out a "real" solution in the next release.

I've moved to the top of the screen the chaos recipe overlay, and from what I've tested, it doesn't block anyhting, except if you have many many auras/buffs actives and the usual timers from Legion, Delirium, etc. but the overlay is still semi-transparent and fade out on mouse hover.

![2021-01-20 10_55_25-YoloCursorOverlay](https://user-images.githubusercontent.com/25111613/105200678-1b435780-5b0e-11eb-8645-7e44f53c1512.png)

Also, there's a "gap" between the overlay and the top of the screen, so if you move your mouse at the very top of the screen, the overlay won't block your clicks (e.g. to move your character, etc.)

**Comment by nomis51** [comment]
Will be fixed in 1.2.10

**Comment by nomis51** [comment]
Based on the update [1.2.16](https://github.com/nomis51/Menagerie/releases/tag/v1.2.16), that let the user move around parts of the overlay, I will try add this feature to the chaos recipe part of the overlay along with a way to display it horizontally or vertically, which will be decent solution I think.

**Comment by nomis51** [comment]
Chaos recipe overlay is now movable and you can now change it's orientation.

Fixed in update 1.3.1
