### ISSUE TITLE
Mention Poe Lurker

### ISSUE THREAD

**Issue by C1rdec** [nomis51/Menagerie#9]
I would like that Poe Lurker & Winook would be mention somewhere since this is a complete rip off.

**Comment by C1rdec** [comment]
Like so.

![image](https://user-images.githubusercontent.com/5436436/106197910-43bbf900-6181-11eb-9cef-7624a2e80f69.png)

**Comment by nomis51** [comment]
Winook and other open-source libraries that are being used in the app will be mentionned in the next readme update.

**Comment by zombodotcom** [comment]
he's the dev of  poe lurker, dont mention his program at all.
